name: Caliper test
version: "2.0.0"

caliper:
  blockchain: fabric
  sutOptions:
    mutualTls: true

channels:
  - channelName: mychannel
    contracts:
      - id: basic

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: "User1"
          clientPrivateKey:
            path: "../test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/4ae764d7e63fdcef74f1791e31ddc6c695c4edb853495da202ecbed0e776e3d9_sk"
          clientSignedCert:
            path: "../test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem"
    connectionProfile:
      path: "../test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml"
      discover: true
